services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - neon-local

  neon-local:
    image: neondatabase/neon_local:latest
    env_file:
      - .env.development
    ports:
      - '5432:5432'
