name: Lint and Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-format:
    name: Lint & Format checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Prettier format check
        run: npm run format:check
        working-directory: ./

      - name: ESLint check
        run: npm run lint --silent
        working-directory: ./

      - name: Upload ESLint report (plain text)
        if: failure()
        run: |
          echo "----- ESLint output (failure) -----"
          npm run lint || true
        working-directory: ./
